#ifndef COLORSCIENCEAPI_ERRORS_H
#define COLORSCIENCEAPI_ERRORS_H


#include "colorscienceapi_global.h"
//#include "colorscienceapi_version.h"

COLORSCIENCEAPI_BEGIN_DECLS


/* Random number to avoid errno conflicts */
#define CS_ERRNOBASE 1122334455

/* Protocol exceptions */
typedef enum {
    CS_EXCEPTION_ILLEGAL_FUNCTION = 0x01,
    CS_EXCEPTION_ILLEGAL_PARAMETER,
    CS_EXCEPTION_ILLEGAL_DATA,
    CS_EXCEPTION_NOT_DEFINED,
    CS_EXCEPTION_POINT_IS_TOO_CLOSE,
    CS_EXCEPTION_POINT_IS_OUTSIDE,
    CS_EXCEPTION_MAX
} cs_exceptions;

#define ECSILFUNC  (CS_ERRNOBASE + CS_EXCEPTION_ILLEGAL_FUNCTION)
#define ECSILPARAM  (CS_ERRNOBASE + CS_EXCEPTION_ILLEGAL_PARAMETER)
#define ECSILDATA  (CS_ERRNOBASE + CS_EXCEPTION_ILLEGAL_DATA)
#define ECSNOTDEFINED  (CS_ERRNOBASE + CS_EXCEPTION_NOT_DEFINED)
#define ECSPOINTISTOOCLOSE  (CS_ERRNOBASE + CS_EXCEPTION_POINT_IS_TOO_CLOSE)
#define ECSPOINTISOUTSIDE  (CS_ERRNOBASE + CS_EXCEPTION_POINT_IS_OUTSIDE)

COLORSCIENCEAPI_END_DECLS


#endif // COLORSCIENCEAPI_ERRORS_H
